
app:
  secret-key: f07b43c9839bbc0a50fead3d59780566b421376dd760f38a1c8956b3dd0e4129
  expiration-time: 3600000

server:
  port: 8090
  servlet:
    context-path: /management

spring:
  sql:
    init:
      mode: always
  main:
    allow-circular-references: true
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    defer-datasource-initialization: true

  datasource:
    driver-class-name: ${DATABASE_DRIVER}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

